fixup! android: Fix Tesseract compile issues.
Enable C++ exceptions when building Tesseract for Android using ndk-build.

When building for an Android app, I got the following error in
thirdparty/tesseract/src/api/baseapi.cpp:
    error: cannot use 'try' with exceptions disabled

This is probably related to commit
20bcbc4058e3767ded293333345f3179726b4de9
which introduced the try/catch in baseapi.cpp that generates the
error.

The Android NDK documentation states that to enable exceptions for a single
module you can add LOCAL_CPP_FEATURES := exceptions or
LOCAL_CPPFLAGS := -fexceptions.
(https://developer.android.com/ndk/guides/cpp-support#xp))

In the latter case, LOCAL_CPPFLAGS is preferable to LOCAL_CXXFLAGS. This
is because LOCAL_CXXFLAGS is specified after LOCAL_CPPFLAGS, which means
that LOCAL_CXXFLAGS can be used to override flags in the LOCAL_CPPFLAGS
when necessary.

But the flag -fexceptions is specified twice when building the module.

If CFLAGS, CPPFLAGS or CXXFLAGS contain "-fexceptions" then the Android
NDK build system appends LOCAL_CPP_FEATURES += exceptions. At this point
NDK also attempts (but fails) to remove -fexceptions from
LOCAL_CPPFLAGS. Later on when the module is being built
LOCAL_CPP_FEATURES is queried, if it contains "exceptions" then the
build system appends LOCAL_CPPFLAGS += -fexceptions. The problem is that
at this point LOCAL_CPPFLAGS still contain the original value, therefore
-fexpection will be given twice in LOCAL_CPPFLAGS.

Without fixing the bug relating to stashing/unstashing LOCAL_* variables,
the simple fix is to leave LOCAL_CPPFLAGS empty and set
LOCAL_CPP_FEATURES := exceptions. Thus when the module is being built
-fexceptions will be appended to the now empty LOCAL_CPPFLAGS, thereby
the flag is only given once.