(recurring semi-random issue with MSVC2022 releases, apparently) hotfix for MSVC2022 which keeps barfing on the fz_invalid_quad constant definition with: error C2099 : initializer is not a constant   -->  compile as C++ in separate source file.    !@#$%   :-(
Also moved the INFINITY and NAN portable defines into mupdf/fitz/geometry.h header file so we don't risk redefining it someplace just ever so slightly differently (D.N.R.Y.)