- updated libraries - fix: error C2512: 'tesseract::STRING': no appropriate default constructor available - fix: tesseract APIs are now in the tesseract namespace - fix: Warning C6001: Using uninitialized memory 'dn'. (libmupdf) - fix for non-writable std::string.data(): change language to CXX17 and C17 in all MSVC projects - disable 'results in undefined behaviour' warning for #define expansions after switching to C17/C++17 language mode in MSVC2019 - fix: warning C4996: 'strdup': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _strdup.   + also fixed for other POSIX functions: fileno(), unlink(), isatty(), ... - fix: MuPDFLib did not have CURL_STATICLIB defined, hence attempted to load the libcurl library as a DLL, resulting in import warnings from the MSVC linker. - fix: warning C5033: 'register' is no longer a supported storage class (CMSREGISTER macro) : https://docs.microsoft.com/en-us/cpp/cpp/storage-classes-cpp?view=msvc-160