work done on wxWidgets et al: compile wxWidgets and wxCharts as monolithic DLLs.
Also some work done on wxFormBuilder + fix for one of the plugin projects ('common') which included the wrong source file. wxFormBuilder finally starts to work, with only a few assertions still firing.

Also fix MSVC fatal error C1128: number of sections exceeded object file format limit: compile with /bigobj -- occurs while compiling wxWidgets_DLL project. References:
- https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/fatal-error-c1128?view=msvc-170
- https://docs.microsoft.com/en-us/cpp/build/reference/bigobj-increase-number-of-sections-in-dot-obj-file?view=msvc-170

Fix wxWidgets project: turns out regiong.cpp is not okay in the jumbo build as some preprocessor macros override thee class defined in there. Issue strangely only surfaces once we start compiling wxWidgets as DLL instead of static library... (hmmmm, is that code touched at all in the demos and samples, then?)