fix stack overflow due to run-away recursion in `pdf_is_ocg_hidden()`. This was fixed by passing along the `cycle_list` properly; we DO realize this MAY be 'counter-indicated' by producing incorrect `pdf_is_ocg_hidden()` check results when using specially crafted recursive logic expressions encoded in the PDF where an `obj` will be evaluated multiple times in the expression.
-------

Crap! Another serious stack overflow!

```
:L#00160: MUTOOL draw -o //?/J:/__bulktest/DATA/__bulktest/TextExtractFiles-T1/pdfium_tests/fx/layer/4_36/FULL-DOC-x300.webp -s mtf -r 300 -y l -P -B 50 pdfium_tests/fx/layer/4_36.pdf
Output format: png (DeviceRGB)
error: cannot find startxref
Exception thrown at 0x00007FFCF45287C6 (MuPDFLib.dll) in bulktest.exe: 0xC00000FD: Stack overflow (parameters: 0x0000000000000001, 0x0000003373503FA0).
Unhandled exception at 0x00007FFCF45287C6 (MuPDFLib.dll) in bulktest.exe: 0xC00000FD: Stack overflow (parameters: 0x0000000000000001, 0x0000003373503FA0).
```

--> stacktrace at the moment of B0RK:

```
MuPDFLib.dll!pdf_cache_object(fz_context * ctx, pdf_document * doc, int num) Line 2302
	at Z:\lib\tooling\qiqqa\MuPDF\source\pdf\pdf-xref.c(2302)
MuPDFLib.dll!pdf_resolve_indirect(fz_context * ctx, pdf_obj * ref) Line 2437
	at Z:\lib\tooling\qiqqa\MuPDF\source\pdf\pdf-xref.c(2437)
MuPDFLib.dll!pdf_resolve_indirect_chain(fz_context * ctx, pdf_obj * ref) Line 2464
	at Z:\lib\tooling\qiqqa\MuPDF\source\pdf\pdf-xref.c(2464)
MuPDFLib.dll!pdf_is_name(fz_context * ctx, pdf_obj * obj) Line 336
	at Z:\lib\tooling\qiqqa\MuPDF\source\pdf\pdf-object.c(336)
MuPDFLib.dll!pdf_is_ocg_hidden_imp(fz_context * ctx, pdf_document * doc, pdf_obj * rdb, const char * usage, pdf_obj * ocg, pdf_cycle_list * cycle_up) Line 641
	at Z:\lib\tooling\qiqqa\MuPDF\source\pdf\pdf-layer.c(641)
MuPDFLib.dll!pdf_is_ocg_hidden(fz_context * ctx, pdf_document * doc, pdf_obj * rdb, const char * usage, pdf_obj * ocg) Line 797
	at Z:\lib\tooling\qiqqa\MuPDF\source\pdf\pdf-layer.c(797)
MuPDFLib.dll!calc_ve_state(fz_context * ctx, pdf_document * doc, pdf_obj * rdb, const char * usage, pdf_obj * ve) Line 580
	at Z:\lib\tooling\qiqqa\MuPDF\source\pdf\pdf-layer.c(580)
MuPDFLib.dll!calc_ve_state(fz_context * ctx, pdf_document * doc, pdf_obj * rdb, const char * usage, pdf_obj * ve) Line 602
	at Z:\lib\tooling\qiqqa\MuPDF\source\pdf\pdf-layer.c(602)
MuPDFLib.dll!pdf_is_ocg_hidden_imp(fz_context * ctx, pdf_document * doc, pdf_obj * rdb, const char * usage, pdf_obj * ocg, pdf_cycle_list * cycle_up) Line 742
	at Z:\lib\tooling\qiqqa\MuPDF\source\pdf\pdf-layer.c(742)
MuPDFLib.dll!pdf_is_ocg_hidden(fz_context * ctx, pdf_document * doc, pdf_obj * rdb, const char * usage, pdf_obj * ocg) Line 797
	at Z:\lib\tooling\qiqqa\MuPDF\source\pdf\pdf-layer.c(797)
MuPDFLib.dll!calc_ve_state(fz_context * ctx, pdf_document * doc, pdf_obj * rdb, const char * usage, pdf_obj * ve) Line 580
	at Z:\lib\tooling\qiqqa\MuPDF\source\pdf\pdf-layer.c(580)
```