added '%O' format to the fz_printf family + used in diagnostic warning message to assist diagnosis. (Made sure the little node dump is AFTER the entire error message, so it remains easily readable!)  See also this excerpt from the lab notes:
-------------

```
:L#00239: MUTOOL show -o "//?/P:/__bulktest-all/DATA/__bulktest/TextExtractFiles-T1/../../SopKonijn/!QIQQA-pdf-watch-dir/2017-03-15/components/tl431 (2)/FULL-DOC.show.txt" -b "../../SopKonijn/!QIQQA-pdf-watch-dir/2017-03-15/components/tl431 (2).pdf" trailer xref pages grep outline js form trailer/* Root/* Root/Metadata 0/* 1/* 2/* 3/* 4/* 5/* 6/* 7/* 8/* 9/* 10/* 11/* 12/* 13/* trailer/Info trailer/Info/Author
warning: non-page object in page tree ({NULL}) -- ignoring the (probably corrupt) fast page tree
warning: Bad or missing last pointer in outline tree, repairing
error: Outline last pointer still bad or missing despite repair
warning: invalid indirect reference (0 0 R)
warning: ... repeated 2 times...
warning: PDF stream Length incorrect
```

... and several more.

#### Conclusion

(Picked that last one for debugging...)

The diagnosis resulted in an addition to the fz_printf() family format: `%O` to print a PDF 'node' as JSON, limited to `width` *lines* and/or ~400 characters: *truncation* of this part will always be clearly indicated in the printf() output.

Meanwhile, it turns out this is another 'currently unsolvable' issue: mupdf recovers well enough and I need to deep-dive the PDF Standard 🥶 *plus* the PDF binary data itself to see if this ITXT/Array thing is kinda okay anyway.

Meanwhile, mupdf-curl.exe renders the PDF beautifully, so we call it a "win" anyhow. 🥳