Enable C++ exceptions when building tesseract for Android using ndk-build
When building for an Android app, I got the following error in
thirdparty/tesseract/src/api/baseapi.cpp:
    error: cannot use 'try' with exceptions disabled

This is probably related to commit
20bcbc4058e3767ded293333345f3179726b4de9
which introduced the try/catch in baseapi.cpp that generates the
error.

The solution is to enable exceptions for tesseract by adding
this to Android.mk:
   LOCAL_CPP_FEATURES += exceptions